# Generated by Django 3.2.4 on 2021-06-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='First name')),
                ('apellido', models.CharField(max_length=255, verbose_name='Last name')),
                ('dni', models.CharField(max_length=10, verbose_name='Dni')),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('imagen', models.ImageField(max_length=254, null=True, upload_to='myphoto/%Y/%m/%d/')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
            ],
        ),
    ]
